### ISSUE TITLE
有些地方的文本没有遮挡

### ISSUE THREAD

**Issue by TCOTC** [zxkmm/siyuan_streamer_mode#1]
- [x] 文档标题
- [x] 文档树的文档标题
- [x] 大纲
- [x] 反链里的内容

   https://github.com/user-attachments/assets/d10a0338-2548-4849-95cf-629f20a1ffcb

**Comment by zxkmm** [comment]
谢谢J佬提醒！那些地方可能还是只能写监听器，可能之后处理

**Comment by zxkmm** [comment]
目前除了反链那个之外其他的都解决了，请问反链那个是怎么触发？

**Comment by TCOTC** [comment]
开启第三个之后反链有遮挡了，但链接还在：


https://github.com/user-attachments/assets/9acc7719-38bb-4ed4-8071-01388ffc5c85

**Comment by zxkmm** [comment]
抱歉，但是“链接还在“这个我没听懂，你指的是：
1. 需要匹配到链接中的关键词就隐藏整个链接？
2. 之前隐藏过链接里的内容，在禁用插件后还造成了影响？

**Comment by TCOTC** [comment]
哦不对，链接这个问题不是反链独有的，所有的链接都还保留着。

你看上个版本的链接是不可点击的：

![image](https://github.com/user-attachments/assets/c6b615f0-c589-4ac9-ac0e-9af5394e85c1)

README：

![image](https://github.com/user-attachments/assets/bb35c6f9-94e0-455a-82c8-d7473515b037)

**Comment by zxkmm** [comment]
哦哦哦抱歉 这个是AI生成的文案所以我没有注意。
上个版本因为改了html所以刚好弄巧成拙阻止了点击（因为链接被弄坏了）
这个可以在讨论一下是要移除这个文案还是阻止带有关键词的链接点击。
感谢纠错！
