### ISSUE TITLE
文档刷新后遮挡就没了

### ISSUE THREAD

**Issue by TCOTC** [zxkmm/siyuan_streamer_mode#2]

**Comment by zxkmm** [comment]
设置里启用了第一个总线对么？理论上刷新应该还有，方便录屏康康么？

**Comment by TCOTC** [comment]
视频能看吗：

https://github.com/user-attachments/assets/2b3f1956-b5d9-4324-854e-ae46c5ba89ce

**Comment by zxkmm** [comment]
目前不能，等我换到Windows上康康

**Comment by zxkmm** [comment]
谢谢，看到视频了。但是这个问题我不能复现。我这边刷新是正常的。
请问启用了哪几个总线监听？

**Comment by TCOTC** [comment]
我才留意到有三个监听，刚刚只开启了第一个

**Comment by TCOTC** [comment]
三个都启用之后只会闪一下了

**Comment by zxkmm** [comment]
~~卧槽，我意识到一个更严重的问题。好像有些时候会把html写到笔记中~~

**Comment by zxkmm** [comment]
https://ld246.com/article/1722442489207

**Comment by TCOTC** [comment]
`loaded-protyle` 行不行？

**Comment by zxkmm** [comment]
谢谢，这两个可以！
